### PR TITLE
Simplify CompositeDisposable::constructor

### PR DESCRIPTION
**Pull request by steelbrain**
```js
function create(){
  return new Set(arguments)
}
```
```js
< create(1,2,3,4)
> Set {1, 2, 3, 4}

< create()
> Set {}
```

[Review on Reviewable](https://reviewable.io/reviews/atom/event-kit/13)

### CODE REVIEW

**Comment by thomasjo** [comment]
Thanks for contributing, but your changes are not valid. This simply doesn't work since `arguments` is not iterable, as you can easily tell by running the specs (just check the failed Travis build if you don't want to run them locally right now).

**Comment by steelbrain** [comment]
@thomasjo the problem is not in the PR but the fact that Atom is running on a super-old Electron version with outdated v8.
If you run the examples in description, It'll work just fine :wink: 
Also I find this super-weird that the same code is working fine for me on my browser JS port of event-kit https://github.com/ZoomPK/event-kit

**Comment by thomasjo** [comment]
The specs are running on Travis against Node v0.12.x, where this does not work. I just tested your PR locally against v0.12.7. It does however work against io.js v2.4.0. So I'll re-open, but we won't be able to merge this for a while. Atom needs to run against a recent io.js first, in addition I think we'll need to wait until io.js and Node.js merge (or practically nobody uses Node.js anymore).

:warning: Do not merge this until aforementioned issues are resolved, or overriding justifications are put forth :warning:

**Comment by steelbrain** [comment]
@thomasjo I just tried it and it works in the latest version of atom.

**Pull request closed without merging**
